name: spritewidget
description: SpriteWidget is an open source toolkit for building complex, high performance animations and 2D games with Flutter.
version: 0.9.23
author: Viktor Lidholt <viktorlidholt@gmail.com>
homepage: https://spritewidget.com/
repository: https://github.com/spritewidget/spritewidget/
issue_tracker: https://github.com/spritewidget/spritewidget/issues
environment:
  sdk: ">=2.2.0 <3.0.0"
  # flutter: ">=1.6.3 <2.0.0"
dependencies:
#  flutter_web: any
#  flutter_web_ui: any
   flutter:
     sdk: flutter
